{% set name = "asynctest" %}
{% set version = "0.11.1" %}
{% set sha256 = "f7ef31994c5e751201bd6ce6f92f60f16ad798bfaed8e2b79a74afaa4475927b" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: "{{ sha256 }}"

build:
  number: 0
  skip: True  # [py<34]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - asynctest

about:
  home: https://github.com/Martiusweb/asynctest/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.md
  summary: Enhance the standard unittest package with features for testing asyncio libraries
  doc_url: http://asynctest.readthedocs.org
  dev_url: https://github.com/Martiusweb/asynctest/

extra:
  recipe-maintainers:
    - hodgsonw
